info:
  app:
    name: afa-discovery
    description: Discovery service
  team:
    name: D2 team

spring:
  application:
    name: afa-discovery
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:cloud}
  security:
    user:
      name: ${EUREKA_CLIENT_USERNAME:eureka_client}
      password: ${EUREKA_CLIENT_PASSWORD:eureka_password}

eureka:
  server:
    metrics:
      enabled: true
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: ${PORT:8761}
