info:
  app:
    name: afa-file
    description: Microloans service
  team:
    name: D2 team

spring:
  application:
    name: afa-file
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

springdoc:
  api-docs:
    enabled: true

server:
  port: ${PORT:8389}
