info:
  app:
    name: afa-process
    description: Afa process service
  team:
    name: D2 team

spring:
  application:
    name: afa-process
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  liquibase:
    liquibaseSchema: migration
    change-log: classpath:/db/changelog/master.yml

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: application

springdoc:
  api-docs:
    enabled: true

server:
  port: ${PORT:8387}
