spring:
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: afa-config

eureka:
  client:
    registry-fetch-interval-seconds: 30
    eureka-server-read-timeout-seconds: 10
    eureka-server-connect-timeout-seconds: 60
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://eureka_client:eureka_password@localhost:8761/eureka}
