spring:
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/afa_user}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}

  liquibase:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/afa_user}
    user: ${DB_USER:username}
    password: ${DB_PASSWORD:password}

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}

  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
