info:
  app:
    name: afa-notification
    description: Microloans service
  team:
    name: D2 team

spring:
  application:
    name: afa-notification
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  mail:
    host: smtp.yandex.ru
    port: 465
    username: oaoaoaoaoaoammmm@yandex.ru
    password: wnjddfavfatwhpda
    protocol: smtps
    debug: true

springdoc:
  api-docs:
    enabled: true
    path: /afa-notification/v3/api-docs

server:
  port: ${PORT:8491}
