spring:
  cloud:
    config:
      enabled: false

  mail:
    host: smtp.yandex.ru
    port: 465
    username: oaoaoaoaoaoammmm@yandex.ru
    password: wnjddfavfatwhpda
    protocol: smtps
    debug: true

  kafka:
    bootstrap-servers: localhost:29092, localhost:29093, localhost:29094
    consumer:
      group-id: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      notification-email-topic: afa-notification-email-topic

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
