spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#  jackson:
#    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${AFA_PROCESS_JDBC_URL:jdbc:postgresql://afa-postgres:5432/afa_process}
    # url: ${AFA_PROCESS_JDBC_URL:jdbc:postgresql://localhost:5432/afa_process}
    username: ${AFA_PROCESS_DB_USER:username}
    password: ${AFA_PROCESS_DB_PASSWORD:password}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      afa-order:
        name: ${AFA_ORDER_NAME:afa-order}
        url: ${AFA_ORDER_URL:afa-order}

  kafka:
    bootstrap-servers: afa-kafka-broker-1:9092, afa-kafka-broker-2:9093, afa-kafka-broker-3:9094
    #bootstrap-servers: localhost:29092, localhost:29093, localhost:29094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      notification-email-topic: afa-notification-email-topic

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always

api:
  job:
    scheduler:
      process-debt: "0 */5 * * * *"
#0 0 0 ? * MON#1
