spring:
  s3:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    # endpoint: ${MINIO_ENDPOINT:http://afa-minio:9000}
    access-key: ${MINIO_ACCESS_KEY:username}
    secret-key: ${MINIO_SECRET_KEY:password}
    bucket: ${MINIO_BUCKET:afa-file}
    region: ${MINIO_REGION:us-east-1}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
