spring:
#  jackson:
#    property-naming-strategy: SNAKE_CASE

  r2dbc:
    url: ${AFA_USER_R2DBC_URL:r2dbc:postgresql://afa-postgres:5432/afa_user}
    # url: ${AFA_USER_R2DBC_URL:r2dbc:postgresql://localhost:5432/afa_user}
    username: ${AFA_USER_DB_USER:username}
    password: ${AFA_USER_DB_PASSWORD:password}

  liquibase:
    url: ${AFA_USER_JDBC_URL:jdbc:postgresql://afa-postgres:5432/afa_user}
    # url: ${AFA_USER_JDBC_URL:jdbc:postgresql://localhost:5432/afa_user}
    user: ${AFA_USER_DB_USER:username}
    password: ${AFA_USER_DB_PASSWORD:password}

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
