info:
  app:
    name: afa-admin
    description: Admin service
  team:
    name: D2 team

spring:
  application:
    name: afa-admin
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:cloud}

server:
  port: ${PORT:8187}
