spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/afa_order}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}

  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
